#!/usr/bin/env python

# Cleans up all the Docker monnezza 

import sys
import subprocess

def call(args):
    return subprocess.call(args.split(' '), stdout=f, stderr=f)

def err():
    print('Command returned non 0 value, see cleanup.log')
    f.write('------ BUILD END ------\n')
    sys.exit(1)


f = open('cleanup.log', 'w')


print('Deleting unused images')
if call('sudo docker image prune -f') != 0:
    err()

print('Deleting unused containers')
if call('sudo docker container prune -f') != 0:
    err()

print('Deleting unused networks')
if call('sudo docker network prune -f') != 0:
    err()
