#!/usr/bin/env python

# Stops all porchetta containers

import sys
import subprocess

def call(args):
    return subprocess.call(args.split(' '), stdout=f, stderr=f)
    
def echo(msg):
    call('echo '+msg+'\n')

def err():
    print('Command returned non 0 value, see stop.log')
    f.write('------ BUILD END ------\n')
    sys.exit(1)


f = open('stop.log', 'w')


msg = 'Stopping twitter module...'
echo(msg)
if call('sudo docker stop -t 10 twitter') != 0:
    err()
    
    
# TODO other modules


msg = 'Stopping main server...'
echo(msg)
if call('sudo docker stop -t 10 mainserver') != 0:
    err()
    
    
msg = 'Stopping rabbitmq...'
echo(msg)
if call('sudo docker stop -t 10 rabbit-mq') != 0:
    err()
   
   
print('OK')
echo('OK')
f.close()
